basket/urls.py
from django.urls import path
from django.views.generic import TemplateView

from basket import views

app_name = 'basket'


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/<int:pk>/', views.BasketAddView.as_view(), name='add-product'),
    path('delete/<int:pk>/', views.BasketDeleteView.as_view(), name='delete-product'),
    path('remove/<int:pk>/', views.RemoveBasketLine.as_view(), name='remove-line'),
    path('changequantity/', views.ChangeQuantity.as_view(), name='changequantity'),
]

basket/templates/basket/index.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load catalog_tags %}
{% load humanize %}
{% block content %}
<section class="sec content_sec">
	<div class="container">

		<ul class="bread">
			<li><a href="">Главная</a></li>
			<li>Корзина</li>
		</ul>

		<h1>Корзина</h1>

		{% comment %}
		<main class="maincol wide w100 white_bg">
			<h3>Ваши дополнительные комбо-бонусы за покупку!</h3>
			<div class="bonus_box">
				<div class="bonus_track">
					<span class="bonus_past"></span>
				</div>
				<div class="bonus_items">
					<div class="bonus_item active">
						<span class="bonus_item-price">0 ₽+</span>
						<span class="bonus_item_circle"><i class="fa fa-check"></i></span>
						<span class="bonus_item-podpis">Бонусов нет</span>
					</div>
					<div class="bonus_item active">
						<span class="bonus_item-price">2500 ₽+</span>
						<span class="bonus_item_circle"><i class="fa fa-check"></i></span>
						<span class="bonus_item-podpis">Бесплатная доставка</span>
					</div>
					<div class="bonus_item active">
						<span class="bonus_item-price">5000 ₽+</span>
						<span class="bonus_item_circle"><i class="fa fa-check"></i></span>
						<span class="bonus_item-podpis">Спеццена ОПТ-2</span>
					</div>
					<div class="bonus_item active">
						<span class="bonus_item-price">10000 ₽+</span>
						<span class="bonus_item_circle"><i class="fa fa-check"></i></span>
						<span class="bonus_item-podpis">Спеццена ОПТ-3</span>
					</div>
					<div class="bonus_item">
						<span class="bonus_item-price">15000 ₽+</span>
						<span class="bonus_item_circle">12455 ₽</span>
						<span class="bonus_item-podpis">Спеццена ОПТ-4</span>
					</div>
					<div class="bonus_item">
						<span class="bonus_item-price">25000 ₽+</span>
						<span class="bonus_item_circle">20455 ₽</span>
						<span class="bonus_item-podpis">Спеццена ОПТ-5</span>
					</div>
				</div>
			</div>
		</main>
		{% endcomment %}

		<main class="maincol wide w100 pad0">
			<div class="bonus_statistic_box">
				<div class="w49 white_bg">
					Вы добавили товар на сумму <b>{{ basket.get_total_sum|floatformat:0|intcomma }} ₽</b>.</b>
					<b><a href="">Перейти в каталог</a></b>
				</div>

				<div class="w49 white_bg">
					<form action="" method="post" class="cupon_form">
						<div class="ip_cell">
							<input type="text" class="input_text" placeholder="Укажите промокод" />
							<!-- <div class="promo_applied">
								<i class="fa fa-check"></i>
								Промокод применён!
							</div> -->
						</div>
						<button class="button medium" type="submit">Применить</button>
					</form>
				</div>
			</div>
		</main>

		<main class="maincol wide w100 white_bg pad0">
			<form action="/checkout" method="get">
			<!-- если надо пересчитать корзину - вызывай функцию calculateFinalPrice() -->
			<table class="cart_table" data-currency=" ₽">
				<tr>
					<th width="180">&nbsp;</th>
					<th>&nbsp;</th>
					<th>Цена за шт.</th>
<!--					<th class="cart_specprice_th">Ваша спеццена <br>ОПТ 1</th>-->
					<th>Количество</th>
					<th>К оплате</th>
					<th>&nbsp;</th>
				</tr>
				{% for line in basket.lines.all %}
				<tr>
					<td>
						<a href="{{ line.product.img.url }}" data-fancybox class="cart_image">
							{% thumbnail line.product.img "140x100" as im %}
							<img src="{{ im.url }}" alt="" />
							{% endthumbnail %}
						</a>
					</td>
					<td class="cart_prod_title"><a href="{% url 'catalog:product-detail' line.product.slug line.product.pk %}">{{ line.product.name }}</a></td>
					<td><span class="cart_mobile_label">Цена за шт.</span><s class="cart_price_old">{{ line.price_excl_tax|floatformat:0|intcomma }} ₽</s></td>
					{% comment %}
					<td class="cart_specprice_th">
						<span class="cart_specprice_box">
							<span class="cart_mobile_label">Ваша спеццена: <span class="border">ОПТ-1</span></span>
							<span class="cart_specprice">0 ₽</span>
<!--							<small>Скидка <br>по промокоду <b>946 ₽</b></small>-->
						</span>
					</td>
					{% endcomment %}

					<td>
						<div class="counter_big_box">
							<button type="button" class="counter_big_ctrl minus">-</button>
							<input type="text" class="counter_big_input" data-product="{{ line.product.pk }}" value="{{ line.quantity }}" data-min="1" data-max="99" />
							<button type="button" class="counter_big_ctrl plus">+</button>
						</div>
					</td>
					<td class="cart_prod_final_price"><span class="cart_mobile_label">К оплате:</span> <b>{{ line.line_price_excl_tax|floatformat:0|intcomma }} ₽</b></td>
					<td><a href="{% url 'basket:remove-line' line.pk %}" class="cart_remove">x</a></td>
				</tr>
				{% endfor %}
				<tr class="cart_totals_row">
					<td colspan="3">
						<div class="cart_itogo_ib">Итого: <b id="total_no_spec">{{ basket.get_total_sum|floatformat:0|intcomma }} ₽</b></div>
<!--						<div class="cart_itogo_ib">Доставка: <b id="delivery_val">120 ₽</b></div> &lt;!&ndash; "Бесплатно"" / текст = 0. main.js &ndash;&gt;-->
					</td>
					<td colspan="4" class="pl0">
						<div class="cart_itogo_final">
							<span class="ib">
								<strong>К оплате: </strong>
							</span>
							<span class="ib cart_final_price" id="total_price">{{ basket.get_total_sum|floatformat:0|intcomma }} ₽</span>
							<button type="submit" class="button cart_order">Оформить заказ</button>
						</div>
					</td>
				</tr>
			</table>
			</form>
		</main>


	</div>
</section>


<section class="sec content_sec white_bg">
	<div class="container">

		<h2 class="sec_title">Успей купить по ШОК-цене</h2>

		<div class="catalog_box items-5">
		{% for sh_prod in shock_price_products %}
			<!-- ITEM -->
			{% include 'catalog/product_card.html' with prod=sh_prod.product %}
		{% endfor %}
		</div>

	</div>
</section>


<section class="sec content_sec">
	<div class="container">

		<h2 class="sec_title have_arrows">Недавно вы смотрели</h2>

		<div class="products_carousel_box">
			{% recently_viewed_products %}
		</div>

	</div>
</section>


{% endblock %}