users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users import views

app_name = 'users'


urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('profile/orders/', views.UserOrderHistoryView.as_view(), name='orders-history'),
]

users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,PermissionsMixin
)


class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **kwargs):
        if not email:
            raise ValueError('Users must have an Email')

        user = self.model(
            email=email,
            **kwargs
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
            email,
            password=password
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(
        max_length=255,
        unique=True,
    )
    first_name = models.CharField('Фамилия', max_length=255, blank=True, null=True)
    last_name = models.CharField('Имя', max_length=255, blank=True, null=True)
    patronymic = models.CharField('Отчество', max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=30,verbose_name="Телефон", null=True, blank=True)
    date_of_birth = models.DateField(verbose_name="Дата рождения",null=True,blank=True)
    last_time_visit = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    @property
    def full_name(self):
        if self.first_name and self.last_name and self.patronymic:
            return '{} {} {}'.format(self.first_name, self.last_name, self.patronymic)
        elif self.first_name and self.last_name:
            return '{} {}'.format(self.first_name, self.last_name)
        elif self.first_name:
            return '{}'.format(self.first_name)
        else:
            return self.email

    @property
    def fio(self):
        return '{} {}'.format(self.first_name, self.last_name)

users/forms.py
from django import forms
from users.models import User


class UserForm(forms.ModelForm):
    phone = forms.CharField(required=True)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'phone',
            'email',
        )

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from order.models import Order


class UserProfileView(LoginRequiredMixin,View):
    template_name = 'users/profile.html'

    def get(self, request, *args, **kwargs):
        return render(request,self.template_name)


class UserOrderHistoryView(LoginRequiredMixin,View):
    template_name = 'users/orders_history.html'

    def get(self, request, *args, **kwargs):
        ctx = {}
        if request.user.is_admin:
            orders = Order.objects.all()
        else:
            orders = request.user.orders.all()
        ctx['orders'] = orders
        return render(request, self.template_name, ctx)


class UserRegisterView(View):
    template_name = 'users/register.html'

    def get(self, request, *args, **kwargs):
        ctx = {}
        return render(request,self.template_name,ctx)


class LoginView(View):
    template_name = 'users/login.html'

    def get(self, request, *args, **kwargs):
        ctx = {}
        return render(request,self.template_name,ctx)

    def post(self, request, *args, **kwargs):
        ctx = {}
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('users:profile')
        else:
            ctx['errors'] = []
        return render(request,self.template_name,ctx)


def logout_view(request):
    logout(request)
    return redirect('/')

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load catalog_tags %}
{% load humanize %}
{% block content %}

<section class="sec bread_sec">
	<div class="container">

		<ul class="bread">
			<li><a href="">Главная</a></li>
			<li>{{ page.menu.title}}</li>
		</ul>

	</div>
</section>


<section class="sec content_sec white_bg">
	<div class="container">
        <div class="contact_form framed">
				<form action="{% url 'users:login' %}" method="post">
					{% csrf_token %}
					<h2>Вход на сайт</h2>
					<div class="contact_form_fields">
						<div class="ip_cell">
							<input type="email" name="email" class="input_text" placeholder="Email">
						</div>
						<div class="ip_cell">
							<input type="password" name="password" class="input_text" placeholder="Пароль">
						</div>
						<div class="ip_cell">
							<button class="button send_button" type="submit"><span class="relative">Отправить</span></button>
						</div>
					</div>
					<div class="agree_row">
						<div class="ib">
							<input type="checkbox" class="ch agree_ch" checked="">
							<label>Я согласен с правилами публикации <br><a href="">пользовательского контента</a>.</label>
						</div>
					</div>
				</form>
			</div>

	</div>
</section>

{% endblock %}

users/templates/users/orders_history.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load catalog_tags %}
{% load humanize %}
{% block content %}


<section class="sec content_sec">
	<div class="container">

		<ul class="bread">
			<li><a href="">Главная</a></li>
			<li>Ваш кабинет</li>
		</ul>

		<h1>Ваш кабинет</h1>

		<aside class="sidebar small">
			<!-- BLOCK -->
			<div class="sidebar_block">
				<ul class="sidebar_menu">
					<li><a href="{% url 'users:profile' %}">Ваши данные</a></li>
					<li class="current"><a href="{% url 'users:orders-history' %}">История заказов</a></li>
					<li><a href="{% url 'users:logout' %}">Выйти из кабинета</a></li>
				</ul>
			</div>
		</aside>

        <main class="maincol wide white_bg pad0">

			<!-- ORDER -->
			<div class="table_box">
			{% for order in orders %}
				<table class="history_table {% if forloop.first %}opened{% endif %}">
				<tbody><tr class="history_headings ">
					<td width="183"><span class="history_number">Заказ №{{ order.pk}}</span></td>
					<td width="300">{{ order.date_placed}}</td>
					<td width="149">{{ order.num_items }} товаров</td>
					<td width="320" colspan="2">{{ order.total_sum_lines|floatformat:0|intcomma }} ₽ <span class="status delivery"></span></td>
					<td><span class="history_arrow"></span></td>
				</tr>
				<tr class="history_details_th">
					<th>&nbsp;</th>
					<th>Название</th>
					<th>Количество</th>
					<th>Цена ед.</th>
					<th>Цена</th>
				</tr>
				{% for line in  order.lines.all %}
				<!-- PRODUCT -->
				<tr class="history_details_product_row">
					<td>
						<a href="" class="history_prod_image">
							{% thumbnail line.product.img "120x86" as im %}
							<img src="{{ im.url }}" alt="" />
							{% endthumbnail %}
						</a>
					</td>
					<td>
						<a href="" class="history_prod_title">{{ line.product }}</a>
					</td>
					<td>{{ line.quantity }}</td>
					<td>{{ line.line_price_excl_tax|floatformat:0|intcomma }}₽</td>
					<td>{{ line.total_line_price|floatformat:0|intcomma }}₽</td>
				</tr>
				{% endfor %}

				<tr class="history_details_itogo">
					<td colspan="3"></td>
					<td>Итого:</td>
					<td colspan="2"><b>{{ order.total_sum_lines|floatformat:0|intcomma }} ₽</b></td>
				</tr>
				<tr class="history_details_itogo">
					<td colspan="3"></td>
					<td>Доставка:</td>
					<td colspan="2"><b>Бесплатно</b></td>
				</tr>
				<tr class="history_details_itogo">
					<td colspan="3"></td>
					<td>К оплате:</td>
					<td colspan="2"><b>{{ order.total_sum_lines|floatformat:0|intcomma }} ₽</b></td>
				</tr>
			</tbody></table>

			{% endfor %}

			</div>


		</main>

	</div>
</section>


{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load catalog_tags %}
{% load humanize %}
{% block content %}


<section class="sec content_sec">
	<div class="container">

		<ul class="bread">
			<li><a href="">Главная</a></li>
			<li>Ваш кабинет</li>
		</ul>

		<h1>Ваш кабинет</h1>

		<aside class="sidebar small">
			<!-- BLOCK -->
			<div class="sidebar_block">
				<ul class="sidebar_menu">
					<li class="current"><a href="{% url 'users:profile' %}">Ваши данные</a></li>
					<li><a href="{% url 'users:orders-history' %}">История заказов</a></li>
					<li><a href="{% url 'users:logout' %}">Выйти из кабинета</a></li>
				</ul>
			</div>
		</aside>


		<main class="maincol wide white_bg">
			<form action="" method="post">
				<section class="form_section">
					<h2>Контактные данные</h2>
					<div class="form_fields personal_info">
						<div class="ip_cell">
							<label class="ip_label">Фамилия:</label>
							<input type="text" class="input_text" placeholder="" value="{{ request.user.first_name }}" disabled />
						</div>
						<div class="ip_cell">
							<label class="ip_label">Телефон:</label>
							<input type="tel" class="input_text" placeholder="" value="{{ request.user.phone }}" disabled />
						</div>

						<div class="ip_cell">
							<label class="ip_label">&nbsp;</label>
							<a href="#" class="button-o medium edit_personal_info">Изменить данные</a>
							<button type="submit" class="button medium save_personal_info">Сохранить</button>
						</div>

						<div class="change_password_box">
							<div class="ip_cell">
								<a href="#" class="change_password_link">Изменить пароль</a>
								<a href="#" class="cancel_change_password_link">Отменить изменение пароля</a>
							</div>
							<div class="change_password_row">
								<div class="ip_cell">
									<input type="password" class="input_text" placeholder="Новый пароль" />
								</div>
								<div class="ip_cell">
									<input type="password" class="input_text" placeholder="Новый пароль" />
								</div>
								<button class="button medium" type="submit">Сохранить</button>
							</div>
						</div>
					</div>
				</section>

				<hr class="minus_padding" />

			</form>
		</main>

	</div>
</section>


{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load catalog_tags %}
{% load humanize %}
{% block content %}

<section class="sec content_sec">
	<div class="container">

		<ul class="bread">
			<li><a href="">Главная</a></li>
			<li>Регистрация</li>
		</ul>

		<h1 class="mb0">Регистрация</h1>

	</div>
</section>

<section class="sec register_sec">
	<div class="container">

		<main class="register_area">
			<div class="register_box">
				<ul class="tabs_nav register_tabs">
					<li><a class="current" href="#tab-1">Физическое лицо</a></li>
				</ul>
				<div class="tabs_container">
					<div class="tab" id="tab-1">
						<form action="" method="post">
							<div class="register_fields">
								<div class="ip_cell">
									<input type="text" class="input_text" placeholder="Имя" />
								</div>
								<div class="ip_cell">
									<input type="email" class="input_text" placeholder="Ваш e-mail" />
								</div>
								<div class="ip_cell">
									<input type="tel" class="input_text" placeholder="Ваш телефон" />
								</div>
							</div>
							<div class="ip_cell agree_box">
								<input type="checkbox" class="ch agree_ch" checked />
								<label>Я соглашаюсь на обработку персональных данных в соответствии с <a href="">Условиями использования сайта</a>,
									<a href="">Политикой обработки персональных данных</a> и на получение сообщений в процессе обработки заказа.</label>
							</div>

							<div class="register_buttons">
								<button type="submit" class="button">Зарегистрироваться</button>
								<a href="#modal_login" class="button-o gray open_modal">Войти</a>
							</div>
						</form>
					</div>

				</div>
			</div>

			<div class="register_info_box">
				<h2>В личном кабинете для Вас будут доступны:</h2>
				<div class="register_info">
					<div class="register_info_row">
						<div class="button"><img src="{% static 'img/i_percent.png' %}" /></div>
						<span>Дополнительные скидки по накопительной программе</span>
					</div>
					<div class="register_info_row">
						<div class="button blue"><img src="{% static 'img/i_pencil.png' %}" /></div>
						<span>Автозаполнение данных при заказе</span>
					</div>
					<div class="register_info_row">
						<div class="button green"><img src="{% static 'img/i_history.png' %}" /></div>
						<span>Ваша история заказов</span>
					</div>
				</div>
			</div>
		</main>

	</div>
</section>

{% endblock %}