catalog/urls.py
from django.urls import path
from django.views.generic import TemplateView

from catalog import views

app_name = 'catalog'


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('product/<int:pk>/reviews/create/', views.ReviewCreateView.as_view(), name='reviews-creater'),
    path('get_filter/', views.FilterAjaxView.as_view(), name='get-filter'),
    path('search/', views.SearchPageView.as_view(), name='search'),
    path('<slug:slug>_<int:pk>.html/', views.ProductDetail.as_view(), name='product-detail'),
    path('<slug:slug>/', views.CategoryDetailView.as_view(), name='category-detail'),
    path('<slug:slug>/<path:path>', views.FilterSeoUrlView.as_view(), name='filter-seo-url'),
]

catalog/templates/catalog/filter_seo_page.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load catalog_tags %}
{% load humanize %}
{% block content %}

<section class="sec content_sec">
	<div class="container">

		<ul class="bread">
			<li><a href="/">Главная</a></li>
			<li>{{ current_category.name }}</li>
		</ul>

		<h1>{{seo_filter_url.h1}}</h1>

		<aside class="sidebar small sidebar_filters">
			<!-- BLOCK -->
			<div class="sidebar_block white_bg no_border">

				<h3 class="mobile1024">Фильтры</h3>

				<a href="#" class="close_modal">x</a>

				<div class="sidebar_inner border_bottom filters_clear_box">
					<button type="button" class="button medium gray clear_filters">Очистить фильтры</button>
				</div>
				<form id="filter-form">
				<input type="hidden" name="category_id" value="{{ current_category.pk }}">
				<ul class="sidebar_menu">
					<li><a href="#">Каталог</a>

						<ul class="sidebar_submenu">
							{% for category in categories %}
							{% if current_category.pk == category.pk %}
								<li class="current"><a href="">{{ category.name }}</a></li>
							{% else %}
								<li><a href="{% url 'catalog:category-detail' category.slug %}">{{ category.name }}</a></li>
							{% endif %}
							{% endfor %}
						</ul>
					</li>

					<li><a href="#">Цена</a>
						<div class="sidebar_subblock">
							<div class="range_inputs">
								<div class="ip_cell">
									<label class="range_label">от</label>
									<input type="text" name="price-min" class="range_input from" data-minvalue="{{ min_price_slider|floatformat:0 }}" value="{{ min_price_slider|floatformat:0 }}" data-value="{{ min_price_slider|floatformat:0 }}" />
								</div>
								<div class="ip_cell">
									<label class="range_label">до</label>
									<input type="text" name="price-max" class="range_input to" data-maxvalue="{{ max_price_slider|floatformat:0 }}" value="{{ max_price_slider|floatformat:0 }}" data-value="{{ max_price_slider|floatformat:0 }}" />
								</div>
							</div>
							<div class="range_slider_box" data-min="{{ min_price_slider|floatformat:0 }}" data-max="{{ max_price_slider|floatformat:0 }}" data-step="100"></div>
						</div>
					</li>

					{% for attr in current_category.attributes.all %}

					<li><a href="#">{{ attr }}</a>
						<div class="sidebar_subblock">
						 {% if attr.is_option %}
							{% with yes_options=filter_result|get_item_int:attr.id %}
							<div class="sidebar_filters_box mCustomScrollbar">
								{% for opt in attr.option_group.options.all %}
								{% if opt.id in yes_options %}

								<span class="ip_checkbox" data-name="">
									<input type="checkbox" {% if opt.id in checked_options|get_item:attr.code %}  checked {% endif %}class="ch filter_checkbox" value="{{ opt.id }}" data-code="{{ opt.code }}" data-name="{{ attr.code }}" name="{{ attr.code }}" />
									<label>{{ opt.option }}</label>
								</span>
								{% endif %}
								{% endfor %}

								<a href="#" class="show_ch_filters">Показать ещё <span>0</span></a>
							</div>
							{% endwith %}
						 {% endif %}

						</div>
					</li>
					{% endfor %}

				</ul>
				</form>
				<div class="sidebar_inner border_top">
					<button type="button" class="button medium gray clear_filters">Очистить фильтры</button>
					<a href="#" class="button filter_results_tag" style="display: none;">Показать <span id="product-count"></span> товара</a>
				</div>
			</div>
		</aside>


		<main class="maincol wide white_bg maincol_filters">
			<a href="#" class="button-o pink medium mobile_filters_button"><img src="{% static 'img/icon_filter.png' %}" /> Фильтры</a>
			<div class="maincol_filters_box">
				<div class="autoScroll">
					{% comment %}
					<div class="ip_maincol_checkbox">
						<input type="checkbox" class="button_filter" />
						<label>Глубокие сковороды</label>
					</div>
					{% endcomment %}

				</div>
			</div>
			<hr class="minus_padding" />
			<div class="maincol_sorting_box">
				<div class="fleft">
					{% comment %}
					<span>Хотите получить скидку на первый заказ? </span>
					<a href="#discount_modal" class="button-o pink discount_button medium open_modal"><i class="fa fa-tag"></i> Хочу скидку</a>
					{% endcomment %}
				</div>
				<div class="fright">
					<!-- переключалки "туглят" класс catalog_view-row у блока catalog_box -->
					<a class="sort_view_link current" href="#view-cell"><i class="fa fa-th"></i></a>
					<a class="sort_view_link" href="#view-row"><i class="fa fa-th-list"></i></a>
					<select name="sort_products" class="input_text small sort_products">
						<option value="price_desc" {% if current_order == "price_desc" %} selected {% endif %}>Сначала дорогие</option>
						<option value="price_asc" {% if current_order == "price_asc" %} selected {% endif %}>Сначала не дорогие</option>
						<option value="new" {% if current_order == "new" %} selected {% endif %}>Сначала новые</option>
					</select>
				</div>
			</div>
		</main>

		<main class="maincol wide pad0">
			<div class="catalog_box">

				{% for prod in products %}
				<!-- ITEM -->
				<div class="product_item incatalog">
					<div class="product_item-icons">
					</div>
					<a href="" class="product_item-image">
						{% thumbnail prod.img "189x135"  as im %}
						<img src="{{ im.url }}" alt="" />
						{% endthumbnail %}
					</a>
					<a href="{% url 'catalog:product-detail' prod.slug prod.pk %}" class="product_item-title">
						{{ prod.name }}
						<span class="product_item-instock">В наличии</span>
					</a>
					<div class="product_item-artnum">Артикул: <span>{{ prod.artikul }}</span></div>
					<div class="product_item-prices">
						{% if prod.price_old %}
						<u class="product_item-price_old">{{ prod.price_old }} ₽</u>
						{% endif %}
						<span class="product_item-price">{{ prod.price|floatformat:0|intcomma }} ₽</span>
					</div>
					<div class="product_item-buttons">
						<span class="product_added">Добавлен в корзину</span>
						<a href="/basket/" data-product="{{ prod.pk }}" class="button-o gray product_item-buy">В корзину</a>
						<div class="product_item-counter_box">
							<div class="counter_box">
								<button type="button" class="counter_ctrl minus">-</button>
								<input type="text" data-product="{{ prod.pk }}" class="counter_input" value="1" data-min="1" data-max="99" />
								<button type="button" class="counter_ctrl plus">+</button>
							</div>
							<a href="/basket/" data-product="{{ prod.pk }}">
							<button class="button add_to_cart_small">
								<img src="{% static 'img/i_cart.png' %}" alt="" />
							</button>
							</a>
							<a href="#" class="close_add_to_cart" data-product="{{ prod.pk }}">x</a>
						</div>
						<a href="#" class="product_item-like add_to_wishlist" data-product="{{ prod.pk }}"><i class="fa fa-heart"></i></a>
					</div>
				</div>

				{% endfor %}


			</div>

			<ul class="paginate">
				{% if products.has_previous %}
				<li class="pg_arrow"><a href="?{% query_transform request page=products.previous_page_number %}"><i class="fa fa-angle-left"></i> назад</a></li>
				{% endif %}
				{% for i in products.paginator.page_range %}
      				{% if products.number == i %}
						<li class="current"><a href="">{{ i }}</a></li>
      				{% else %}
        				<li><a href="?{% query_transform request page=i %}">{{ i }}</a></li>
      				{% endif %}
    			{% endfor %}
				{% if products.has_next %}
				<li class="pg_arrow"><a href="?{% query_transform request page=products.next_page_number %}"><i class="fa fa-angle-right"></i> вперед</a></li>
				{% endif %}
			</ul>

			<div class="catalog_description">
				<h2 class="catalog_desc-title">{{ seo_filter_url.h1 }}</h2>

				{{ seo_filter_url.seo_text }}

			</div>
		</main>

	</div>
</section>

{% endblock %}

catalog/templates/catalog/index.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load catalog_tags %}
{% load humanize %}
{% block content %}

<section class="sec content_sec">
	<div class="container">

		<ul class="bread">
			<li><a href="/">Главная</a></li>
			<li>{{ current_category.name }}</li>
		</ul>

		<h1>{{ current_category.name }}</h1>

		<aside class="sidebar small sidebar_filters">
			<!-- BLOCK -->
			<div class="sidebar_block white_bg no_border">

				<h3 class="mobile1024">Фильтры</h3>

				<a href="#" class="close_modal">x</a>

				<div class="sidebar_inner border_bottom filters_clear_box">
					<button type="button" class="button medium gray clear_filters">Очистить фильтры</button>
				</div>
				<form id="filter-form">
				<input type="hidden" name="category_id" value="{{ current_category.pk }}">
				<ul class="sidebar_menu">
					<li><a href="#">Каталог</a>

						<ul class="sidebar_submenu">
							{% for category in categories %}
							{% if current_category.pk == category.pk %}
								<li class="current"><a href="">{{ category.name }}</a></li>
							{% else %}
								<li><a href="{% url 'catalog:category-detail' category.slug %}">{{ category.name }}</a></li>
							{% endif %}
							{% endfor %}
						</ul>
					</li>

					<li><a href="#">Цена</a>
						<div class="sidebar_subblock">
							<div class="range_inputs">
								<div class="ip_cell">
									<label class="range_label">от</label>
									<input type="text" name="price-min" class="range_input from" data-minvalue="{{ min_price_slider|floatformat:0 }}" value="{{ min_price_slider|floatformat:0 }}" data-value="{{ min_price_slider|floatformat:0 }}" />
								</div>
								<div class="ip_cell">
									<label class="range_label">до</label>
									<input type="text" name="price-max" class="range_input to" data-maxvalue="{{ max_price_slider|floatformat:0 }}" value="{{ max_price_slider|floatformat:0 }}" data-value="{{ max_price_slider|floatformat:0 }}" />
								</div>
							</div>
							<div class="range_slider_box" data-min="{{ min_price_slider|floatformat:0 }}" data-max="{{ max_price_slider|floatformat:0 }}" data-step="100"></div>
						</div>
					</li>

					{% for attr in current_category.attributes.all %}

					<li><a href="#">{{ attr }}</a>
						<div class="sidebar_subblock">
						 {% if attr.is_option %}
							{% with yes_options=filter_result|get_item_int:attr.id %}
							<div class="sidebar_filters_box mCustomScrollbar">
								{% for opt in attr.option_group.options.all %}
								{% if opt.id in yes_options %}

								<span class="ip_checkbox" data-name="">
									<input type="checkbox" {% if opt.id in checked_options|get_item:attr.code %}  checked {% endif %}class="ch filter_checkbox" value="{{ opt.id }}" data-name="{{ attr.code }}" data-code="{{ opt.code }}" name="{{ attr.code }}" />
									<label>{{ opt.option }}</label>
								</span>
								{% endif %}
								{% endfor %}

								<a href="#" class="show_ch_filters">Показать ещё <span>0</span></a>
							</div>
							{% endwith %}
						 {% endif %}

						</div>
					</li>
					{% endfor %}

				</ul>
				</form>
				<div class="sidebar_inner border_top">
					<button type="button" class="button medium gray clear_filters">Очистить фильтры</button>
					<a href="#" class="button filter_results_tag" style="display: none;">Показать <span id="product-count"></span> товара</a>
				</div>
			</div>
		</aside>


		<main class="maincol wide white_bg maincol_filters">
			<a href="#" class="button-o pink medium mobile_filters_button"><img src="{% static 'img/icon_filter.png' %}" /> Фильтры</a>
			<div class="maincol_filters_box">
				<div class="autoScroll">
					{% comment %}
					<div class="ip_maincol_checkbox">
						<input type="checkbox" class="button_filter" />
						<label>Глубокие сковороды</label>
					</div>
					{% endcomment %}

				</div>
			</div>
			<hr class="minus_padding" />
			<div class="maincol_sorting_box">
				<div class="fleft">
					{% comment %}
					<span>Хотите получить скидку на первый заказ? </span>
					<a href="#discount_modal" class="button-o pink discount_button medium open_modal"><i class="fa fa-tag"></i> Хочу скидку</a>
					{% endcomment %}
				</div>
				<div class="fright">
					<!-- переключалки "туглят" класс catalog_view-row у блока catalog_box -->
					<a class="sort_view_link current" href="#view-cell"><i class="fa fa-th"></i></a>
					<a class="sort_view_link" href="#view-row"><i class="fa fa-th-list"></i></a>
					<select name="sort_products" class="input_text small sort_products">
						<option value="price_desc" {% if current_order == "price_desc" %} selected {% endif %}>Сначала дорогие</option>
						<option value="price_asc" {% if current_order == "price_asc" %} selected {% endif %}>Сначала не дорогие</option>
						<option value="new" {% if current_order == "new" %} selected {% endif %}>Сначала новые</option>
					</select>
				</div>
			</div>
		</main>

		<main class="maincol wide pad0">
			<div class="catalog_box">

				{% for prod in products %}
				<!-- ITEM -->
				<div class="product_item incatalog">
					<div class="product_item-icons">
					</div>
					<a href="" class="product_item-image">
						{% thumbnail prod.img "189x135"  as im %}
						<img src="{{ im.url }}" alt="" />
						{% endthumbnail %}
					</a>
					<a href="{% url 'catalog:product-detail' prod.slug prod.pk %}" class="product_item-title">
						{{ prod.name }}
						<span class="product_item-instock">В наличии</span>
					</a>
					<div class="product_item-artnum">Артикул: <span>{{ prod.artikul }}</span></div>
					<div class="product_item-prices">
						{% if prod.price_old %}
						<u class="product_item-price_old">{{ prod.price_old }} ₽</u>
						{% endif %}
						<span class="product_item-price">{{ prod.price|floatformat:0|intcomma }} ₽</span>
					</div>
					<div class="product_item-buttons">
						<span class="product_added">Добавлен в корзину</span>
						<a href="/basket/" data-product="{{ prod.pk }}" class="button-o gray product_item-buy">В корзину</a>
						<div class="product_item-counter_box">
							<div class="counter_box">
								<button type="button" class="counter_ctrl minus">-</button>
								<input type="text" data-product="{{ prod.pk }}" class="counter_input" value="1" data-min="1" data-max="99" />
								<button type="button" class="counter_ctrl plus">+</button>
							</div>
							<a href="/basket/" data-product="{{ prod.pk }}">
							<button class="button add_to_cart_small">
								<img src="{% static 'img/i_cart.png' %}" alt="" />
							</button>
							</a>
							<a href="#" class="close_add_to_cart" data-product="{{ prod.pk }}">x</a>
						</div>
						<a href="#" class="product_item-like add_to_wishlist" data-product="{{ prod.pk }}"><i class="fa fa-heart"></i></a>
					</div>
				</div>

				{% endfor %}


			</div>


			<ul class="paginate">
				{% if products.has_previous %}
					<li class="pg_arrow"><a href="?{% query_transform request page=products.previous_page_number %}"><i class="fa fa-angle-left"></i> назад</a></li>
				{% endif %}
				{% for i in products.paginator.page_range %}
      				{% if products.number == i %}
						<li class="current"><a href="">{{ i }}</a></li>
      				{% else %}
        				<li><a href="?{% query_transform request page=i %}">{{ i }}</a></li>
      				{% endif %}

    			{% endfor %}
				{% if products.has_next %}
					<li class="pg_arrow"><a href="?{% query_transform request page=products.next_page_number %}"><i class="fa fa-angle-right"></i> вперед</a></li>
				{% endif %}
			</ul>

			<div class="catalog_description">
				<h2 class="catalog_desc-title">{{ current_category.name }}</h2>

				{{ current_category.description }}

			</div>
		</main>

	</div>
</section>

{% endblock %}

catalog/templates/catalog/product.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load catalog_tags %}
{% load humanize %}
{% block content %}
<section class="sec bread_sec">
	<div class="container">
		
		<ul class="bread">
			<li><a href="/">Главная</a></li>
			<li><a href="{% url 'catalog:category-detail' product.category.slug %}">{{ product.category.name }}</a></li>
			<li>{{ product.name }}</li>
		</ul>

	</div>
</section>

<section class="sec product_sec">
	<div class="container">
		
		<main class="product_box">
			<div class="product_img_data">
				<div class="product_titles">
					<a href="#" class="product_like product_item-like add_to_wishlist"  data-product="{{ product.pk }}"><i class="fa fa-heart-o"></i></a>
					<!-- <a href="" class="product_like liked"><i class="fa fa-heart"></i></a> -->
					<h1>{{ product.name }}</h1>
					<div class="artikul">Артикул: {{ product.artikul}}</div>
				</div>
				<div class="product_flex_box">
					<div class="product_images_box">
						<a href="{{ product.img.url }}" class="product_main_image fancy" data-fancybox="product">
							{% thumbnail product.img "200x200"  as im %}
							<img src="{{ im.url }}" alt="" />
							{% endthumbnail %}
						</a>
					</div>

					<div class="product_info_box">

						<article class="product_desc">
							<p>Описание</p>

						</article>
						<div class="product_anchors">
							<a href="#specs" class="product_anchor">Харакетристики</a>
							<a href="#reviews" class="product_anchor">{{ product.reviews.count }} отзывов</a>
						</div>
					</div>
				</div>
			</div>
			
			<div class="product_details_box">
				<div class="product_badges">
					<span class="instock">В наличии</span>
					<!-- <span class="instock not">Нет в наличии</span> -->
<!--					<div class="beidge shock">Шок цена</div>-->
				</div>
				<div class="product_price_box">
					{% if product.price_old %}
						<s class="product_price_old">{{ product.price_old|floatformat:0|intcomma }} ₽</s>
					{% endif %}
					<div class="product_price">{{ product.price|floatformat:0|intcomma }} ₽</div>
				</div>
				{% comment %}}
				<div class="product_promocode_box">
					<span class="note">Используй промокод в корзине, чтобы получить скидку</span>
					<span class="promocode">LETO395</span>
				</div>
				{% endcomment %}

				<table class="product_table_prices">
				</table>

				<div class="product_buttons">
					<div class="counter_big_box">
						<button type="button" class="counter_big_ctrl minus">-</button>
						<input type="text" class="counter_big_input" value="1" data-min="1" data-max="99" />
						<button type="button" class="counter_big_ctrl plus">+</button>
					</div>
					<a href="#" class="button medium product-buy" data-product="{{product.pk}}">В корзину</a>
					<a href="/basket" class="button medium to-basket" style="display: none;" data-product="{{product.pk}}">Перейти в корзину</a>
				</div>

				<!-- <div class="product_buttons not_available">
					<input type="text" class="input_text centered" placeholder="Введите E-mail" />
					<button class="button medium" type="submit">Уведомить о поступлении</button>
				</div> -->
			</div>


		</main>

	</div>
</section>


<section class="sec content_sec" id="specs">
	<div class="container">

		<div class="sidebar_block important mobile1024">
			<div class="sidebar_inner">
				<div class="free_delivery_titles">
					<div class="button"><img src="{% static 'img/i_truck.png' %}" alt=""></div>
					<strong>Бесплатная доставка при заказе от 2500 ₽</strong>
				</div>
				<div class="podpis pad0">
					Текст про бесплатную доставку. Мы исследовали цены на этот товар в 7 интернет-магазинах и нашли для вас наиболее интересную.
				</div>
			</div>
		</div>
		
		<h2 class="h1">Характеристики</h2>

		<div class="flex_1300">
		<main class="maincol product_specs_box">
			<table class="zebra no_border">
				<tbody>
					{% for pav in product.attribute_values.all %}
					<tr>
						<td>{{ pav.attribute.name}}:</td>
						<td><b>{{ pav.value_option }}</b></td>
					</tr>
					{% endfor %}

				</tbody>
			</table>

			<section class="reviews_box" id="reviews">
				<div class="reviews_titles_row">
					<h2 class="h1">Отзывы <span class="reviews_count">{{ product.get_reviews_approved.count }}</span></h2>
					<a href="#write_review_modal" class="button blue medium open_modal">Написать отзыв</a>
				</div>
				<div class="reviews_list">
					{% for review in product.get_reviews_approved %}
					<!-- ITEM -->
					<article class="review_item">
						<div class="review_details">
							<div class="review_author">
								<span class="author_first_letter">{{ review.first_name|make_list|first }}</span>
								<span><strong>{{ review.first_name }}</strong></span>
							</div>
							<span class="review_date">{{ review.created_at}}</span>
						</div>
						<div class="review_desc">
							<p><strong>Достоинства:</strong><br>
							{{ review.advantages}}</p>
							<p><strong>Недостатки:</strong><br>
							{{ review.disadvantages }}.</p>
						</div>

					</article>
					{% endfor %}

				</div>
			</section>
			{% if product.reviews.count > 10 %}
			<a href="" class="button gray medium w100 show_reviews">Смотреть ещё отзывы</a>
			{% endif %}
		</main>


		<aside class="sidebar">

			<!-- BLOCK -->
			<div class="sidebar_block important">
				<div class="sidebar_inner">
					<div class="free_delivery_titles">
						<div class="button"><img src="{% static 'img/i_truck.png' %}" alt=""></div>
						<strong>Бесплатная доставка при заказе от 2500 ₽</strong>
					</div>
					<div class="podpis pad0">
						Текст про бесплатную доставку. Мы исследовали цены на этот товар в 7 интернет-магазинах и нашли для вас наиболее интересную.
					</div>
				</div>
			</div>

			<!-- BLOCK -->
			<img src="{% static 'img/sidebar_banner.jpg' %}" alt="" class="sidebar_block" />

			<!-- BLOCK -->
			<div class="sidebar_block carousel">
				<ul class="single_prod_slider arrowsNav owl-carousel">

					<li class="item"></li>
					
				</ul>
			</div>

		</aside>
		</div>

	</div>
</section>




{% if product.primary_recommendations.count > 0 %}
<section class="sec content_sec white_bg">
	<div class="container">
		<h2 class="sec_title">Похожие товары</h2>
		<div class="catalog_box items-5">
			{% for prod in product.primary_recommendations.all %}
				{% include 'catalog/product_card.html' with prod=prod.recommendation %}
			{% endfor %}
		</div>
	</div>
</section>
{% endif %}



<section class="sec content_sec">
	<div class="container">

		<h2 class="sec_title">Недавно вы смотрели</h2>
		
		<div class="products_carousel_box">
			{% recently_viewed_products current_product=product %}
		</div>

	</div>
</section>


<div class="modal" id="write_review_modal">
	<div class="modal_content">
		<h2 class="modal_title centered">
			Отзыв о товаре
			<span class="modal_subtitle">{{ product.name }}</span>
		</h2>
		<a href="#" class="modal_close">x</a>
		<div>
			<form action="/catalog/product/{{ product.pk }}/reviews/create/" method="post" id="write_review_form_modal">
			<p>Благодарим за выбор нашего товара. Пожалуйста, оставьте  честное мнение о товаре, чтобы другим покупателям было проще сделать выбор.</p>
			<div class="ip_cell">
				<input type="text" name="first_name" class="input_text" placeholder="Имя *" />
			</div>
			<div class="ip_cell">
				<input type="email" name="email" class="input_text" placeholder="E-mail (не будет опубликован) *" />
			</div>
			<div class="ip_cell">
				<textarea class="input_text" name="advantages" placeholder="Опишите, что вам особенно понравилось."></textarea>
			</div>
			<div class="ip_cell">
				<textarea class="input_text" name="disadvantages" placeholder="Напишите, есть ли какие-то минусы у товара."></textarea>
			</div>
			<div class="modal_buttons">
				<button class="button medium send_button" type="submit">Отправить отзыв</button>
			</div>
			<div class="ip_cell agree_box agree_photos">
				<input type="checkbox" class="ch agree_ch" checked />
				<label>Я согласен с правилами публикации пользовательского контента.</label>
			</div>
		</form>
		</div>
	</div>
	<div class="modal_overlay"></div>
</div>

{% endblock %}

catalog/templates/catalog/product_card.html
{% load static %}
{% load humanize %}
{% load thumbnail %}
<div class="product_item incatalog">
    <div class="product_item-icons">
    </div>
    <a href="" class="product_item-image">
        {% thumbnail prod.img "189x135" as im %}
        <img src="{{ im.url }}" alt="" />
        {% endthumbnail %}
    </a>
    <a href="{% url 'catalog:product-detail' prod.slug prod.pk %}" class="product_item-title">
        {{ prod.name }}
        <span class="product_item-instock">В наличии</span>
    </a>
    <div class="product_item-artnum">Артикул: <span>{{ prod.artikul }}</span></div>
    <div class="product_item-prices">
        {% if prod.price_old %}
        <u class="product_item-price_old">{{ prod.price_old|floatformat:0|intcomma }} ₽</u>
        {% endif %}
        <span class="product_item-price">{{ prod.price|floatformat:0|intcomma }} ₽</span>
    </div>
        <div class="product_item-buttons">
            <span class="product_added">Добавлен в корзину</span>
            <a href="/basket/" data-product="{{ prod.pk }}" class="button-o gray product_item-buy">В корзину</a>
            <div class="product_item-counter_box">
                <div class="counter_box">
                    <button type="button" class="counter_ctrl minus">-</button>
                    <input type="text" data-product="{{ prod.pk }}" class="counter_input" value="1" data-min="1" data-max="99" />
                    <button type="button" class="counter_ctrl plus">+</button>
                </div>
                <a href="/basket/" data-product="{{ prod.pk }}">
                <button class="button add_to_cart_small">
                    <img src="{% static 'img/i_cart.png' %}" alt="" />
                </button>
                </a>
                <a href="#" class="close_add_to_cart" data-product="{{ prod.pk }}">x</a>
            </div>
            <a href="#" class="product_item-like add_to_wishlist {% if is_liked %}liked{% endif %}" data-product="{{ prod.pk }}"><i class="fa fa-heart"></i></a>
        </div>
</div>

catalog/templates/catalog/search_page.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% load catalog_tags %}
{% load humanize %}
{% block content %}
<section class="sec content_sec">
	<div class="container">

		<ul class="bread">
			<li><a href="">Главная</a></li>
			<li>Поиск</li>
		</ul>

		<h1>Поиск</h1>

		<main class="maincol wide white_bg">
			<div class="search_result_msg">
				По вашему запросу <span class="tpink">“{{ search_term }}”</span> найдено {{ search_count }} товаров:
			</div>
		</main>

		<main class="maincol wide pad0">
			<div class="catalog_box">
               {% for prod in products %}
                {% include 'catalog/product_card.html' %}
                {% endfor %}

				<ul class="paginate">
				<li class="pg_arrow"><a href=""><i class="fa fa-angle-left"></i></a></li>
				{% for i in products.paginator.page_range %}
      				{% if products.number == i %}
						<li class="current"><a href="">{{ i }}</a></li>
      				{% else %}
        				<li><a href="?{% query_transform request page=i %}">{{ i }}</a></li>
      				{% endif %}
    			{% endfor %}
				<li class="pg_arrow"><a href=""><i class="fa fa-angle-right"></i></a></li>
			</ul>

			</div>

		</main>
	</div>
</section>
{% endblock %}